DELETE FROM Customer;
DELETE FROM Orders;
DELETE FROM PaymentType;
DELETE FROM ProductOrder;
DELETE FROM Product;

DROP TABLE IF EXISTS Customer;
DROP TABLE IF EXISTS Orders;
DROP TABLE IF EXISTS PaymentType;
DROP TABLE IF EXISTS ProductOrder;
DROP TABLE IF EXISTS Product;

CREATE TABLE Customer (
	CustomerID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	Name TEXT NOT NULL,
	Address TEXT NOT NULL,
	City TEXT NOT NULL,
	State TEXT NOT NULL,
	Zip INT NOT NULL,
	Telephone INT NOT NULL,
	Active BIT NULL DEFAULT 0
);

CREATE TABLE Orders (
	OrderID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	CustomerID INTEGER NOT NULL,
	PaymentTypeID INTEGER,

	FOREIGN KEY (CustomerID) REFERENCES Customer(CustomerID)
);

CREATE TABLE PaymentType (
	PaymentTypeID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	PaymentName TEXT NOT NULL,
	AccountNumber INT NOT NULL,
	CustomerID INTEGER NOT NULL,

	FOREIGN KEY (CustomerID) REFERENCES Customer(CustomerID)
);

CREATE TABLE ProductOrder (
	ProductOrderID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	ProductID INT NOT NULL,
	OrderID INT NOT NULL,

	FOREIGN KEY (OrderID) REFERENCES Orders(OrderID),
	FOREIGN KEY (ProductID) REFERENCES Product(ProductID)
);

CREATE TABLE Product (
	ProductID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	ProductName TEXT NOT NULL,
	Product_Price INT NOT NULL
);

